[pecas]

[pecas.T]
blocos = [
	"010", "111", "000"
]

[pecas.I]
blocos = [
	"00000","00000", "11111", "00000", "00000"
]

[pecas.O]
blocos = [
	"11","11"
]

[pecas.J]
blocos = [
	"100","111","000"
]

[pecas.L]
blocos = [
	"001","111","000"
]

[pecas.S]
blocos = [
	"011","110","000"
]

[pecas.Z]
blocos = [
	"110","011","000"
]
